config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  devise_for :users
  root to: 'spots#index'
  resources :users, only: :show
  resources :spots do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
    {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
    {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
    {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
    {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
    {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
    {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
    {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
    {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
    {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
    {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
    {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
    {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
    {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
    {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
    {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
    ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :spot
  belongs_to :user 
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '温泉' },
    { id: 2, name: 'ショッピング' },
    { id: 3, name: '体験' },
    { id: 4, name: '歴史' },
    { id: 5, name: 'スポーツ' },
    { id: 6, name: '博物館、美術館、記念館' },
    { id: 7, name: '学び' },
    { id: 8, name: 'グルメ' },
    { id: 9, name: '天体観測' },
    { id: 10, name: 'その他' },
  ]
  end

app/models/location.rb
class Location < ActiveHash::Base
  self.data = [
    { id: 1, name: '海' },
    { id: 2, name: '山' },
    { id: 3, name: '街' },
    { id: 4, name: '川' },
    { id: 5, name: '滝' },
    { id: 6, name: 'その他' },
  ]
  end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :comments
  belongs_to :user
  has_one_attached :image
  # has_one_attached :ファイル名
  # Active Storageのテーブルとspotsテーブルのアソシエーションを定義した。
  # spots_controller.rbにて、imageカラムの保存を許可(ストロングパラメーター)

  # アクティブハッシュのアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :city
  belongs_to_active_hash :location
  belongs_to_active_hash :genre
  # アクティブハッシュのアソシエーション



  # バリデーション
  with_options presence: true do
    validates :image
    validates :title
    # validates :country
    validates :description
    # validates :city_id
    # validates :genre_id
    # validates :location_id
    validates :price
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spots
  has_many :comments

  with_options presence: true do
    validates :nickname
    validates :password,format: {with:/\A[a-zA-Z0-9]+\z/,length:{minimum:6}, message:"パスワードは6文字以上で半角英数字混合で入力してください"}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/spots/#{comment.spot.id}"
    # ここはprefixでもいける？
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, spot_id: params[:spot_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!,except: [:index,:show,:search]
  before_action :set_spot, only: [:edit, :show, :update,:destroy]  
  before_action :search_spot, only: [:index, :search]

  def index
    @spots = Spot.all.page(params[:page]).per(9)
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.create(spot_params)
    if @spot.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @spot.comments.includes(:user)
  end

  def edit
  end

  def update
    if @spot.update(spot_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @spot.destroy
      redirect_to root_path
    else
      redirect_to spot_path(@spot.id)
    end
  end

  def search
    @spots = @p.result(params[:page]).per(9)
  end
  
  
  private
  def spot_params
    params.require(:spot).permit(:title,:image,:description,:price,:city_id).merge(user_id: current_user.id)
  end
  
  def set_spot
    @spot = Spot.find(params[:id])
  end
  # edit, :show, :update,:destroyをまとめている
  
  def search_spot
    @p = Spot.ransack(params[:q])  # 検索オブジェクトを生成
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @spots = user.spots
  end
end
# 応用カリキュラムを参照。

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trip29798</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <%# <%= link_to image_tag("神戸街並み.jpg", class:"logo-white"), "#" %> 
  <p>© GO TO HYOGO</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header wrapper'>
  <%= link_to 'GO GO BOARD', root_path, class: "title" %>

  <nav>
    <ul class="main-nav">
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% if user_signed_in?%>
        <li><%= link_to current_user.nickname, new_user_session_path, class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
        <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
    </ul>
  </nav>
</header>




    

app/views/spots/edit.html.erb
<%= render "shared/header" %>

  <div class="spot-main">
    <%= form_with(model: @spot, local: true, class: "spot-form") do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <h2>投稿画像</h2>
      <div class="click-upload">
        <%= f.file_field :image, id:"spot-image" %>
      </div>

      <div class="new-spots">
        <h2>タイトル入力欄</h2>
        <%= f.text_field :title, class:"spots-text", placeholder: "タイトルを入れて下さい" %>
      </div>

      <%# <h2 class="spot-category">投稿詳細</h2> %>
      <div class="pulldown-spots">
        <div class="pulldown">
          <h2>市</h2>
          <%= f.collection_select(:city_id, City.all, :id, :name, {}, {class:"select-box", id:"spot-category"}) %>
          <h2>ロケーション</h2>
          <%= f.collection_select(:location_id, Location.all, :id, :name, {}, {class:"select-box", id:"spot-category"}) %>
          <h2>ジャンル</h2>
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"spot-category"}) %>
        </div>
      </div>

      <div class = "spots-price-box">
        <h2>一人当たりの入場料、予算</h2>
        <%= f.text_field :price, class:"spots-price", placeholder: "半角数字のみ入力して下さい" %>
      </div>

      <div class="new-spots">
      <h2>コメント入力欄</h2>
        <%= f.text_area :description, class:"spots-text", placeholder: "感想を入力して下さい" %>
      </div>
      <div class="spot-btn-contents">
        <%= f.submit "投稿する" ,class:"spot-btn" %>
      </div>
    <% end %>
  </div>
<%= render "shared/footer" %>

app/views/spots/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="main-content wrapper">
    <h2 class="page-title">Have a nice trip!</h2>
    <p>みんなでスケボーを練習する場所を共有しましょう。
    </p>

    <%# 検索バー %>
    <%= search_form_for @p, url: search_spots_path do |f| %>
      <div class = "search-keyword-index">
        <%= f.search_field :description_or_title_cont, placeholder:"キーワード" %>
        <%= f.submit '検索' %>
      </div>
    <% end  %>
    <%# 検索バー %>

    <%# カメラ新規投稿 %>
    <div class='purchase-btn1'>
      <a href="/spots/new">
        <%= image_tag 'camera.png' , size: '120x120' ,class: "purchase-btn-icon" %>
      </a>
      <p>↑投稿する↑</p>
    </div>
    <%# カメラ新規投稿 %>
  


    <%# 画像一覧 %>

    <%# <div class="image"> %>
      <% @spots.each do |spot| %>
        <%= link_to spot_path(spot.id) do %>
          <div class="card-deck">
            <div class="card" style="width: 18rem;">
              <%= image_tag spot.image, class: 'card-img-top',  width:"100%", height:"240" %>
              <div class="card-body">
                <h5 class="card-title"><%= spot.title %></h5>
                <p class="card-text"><%= link_to spot.user.nickname, user_path(spot.user_id) %></p>
                <p class="card-text"><%= spot.price %>円</p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <%# </div> %>

    <%# 画像投稿 %>
    <div class="main-content wrapper">
      <div class='purchase-btn2'>
        <a href="/spots/new">
          <%= image_tag 'camera.png' , size: '120x120' ,class: "purchase-btn-icon" %>
        </a>
        <p>↑投稿する↑</p>
      </div>
    </div>
    <%# 画像投稿 %>
  </div>
  <%= paginate @spots %>
</div>
<%= render "shared/footer" %>

app/views/spots/new.html.erb
<%= render "shared/header" %>

  <div class="spot-main">
    <%= form_with(model: @spot, local: true, class: "spot-form") do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <h2>投稿画像</h2>
      <div class="click-upload">
        <%= f.file_field :image, id:"spot-image" %>
      </div>

      <div class="new-spots">
        <h2>施設名入力欄</h2>
        <%= f.text_field :title, class:"spots-text", placeholder: "タイトルを入れて下さい" %>
      </div>

      <div class = "spots-price-box">
        <h2>一人当たりの予算</h2>
        <%= f.text_field :price, class:"spots-price", placeholder: "半角数字のみ入力して下さい" %>
      </div>

      <div class = "spots-price-box">
        <h2>住所</h2>
        <%= f.collection_select(:city_id, City.all, :id, :name, {include_blank: '指定なし'}, {class:"select-box", id:"spot-category"}) %>
      </div>

      <div class="new-spots">
        <h2>メモ入力欄</h2>
        <%= f.text_area :description, class:"form-control", placeholder: "感想を入力して下さい" %>
      </div>


      <div class="spot-btn-contents">
        <%= f.submit "投稿する" ,class:"spot-btn" %>
      </div>
    <% end %>
  </div>
<%= render "shared/footer" %>

app/views/spots/search.html.erb
<%= render "shared/header" %>

<div class="main">
  <%= search_form_for @p, url: search_spots_path do |f| %>
    <div class = "search-keyword">
      <%= f.search_field :description_cont, placeholder:"キーワード" %>
      <%= f.submit '検索' %>
    </div>
  <% end %>


  <div class="contents">
    <div class="grid">
      <% @spots.each do |spot| %>
        <%= link_to spot_path(spot.id) do %>
          <div class="index-spot">
            <%= image_tag spot.image, class: "spot-img"%>
            <p><%= spot.title %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>  
</div>

<%= render "shared/footer" %>

app/views/spots/show.html.erb
<%= render "shared/header" %>


<div class="main">
  <div class="spot-show">
    <div class="container py-4" id="works">
      <div class="card-deck">
        <div class="card">
          <%= image_tag @spot.image ,class:"card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= @spot.title %></h5>
            <p class="card-text"><%= @spot.description %></p>
          </div>
        </div>
      </div>
    </div>

    <h1 class="spot-midasi">投稿してくれた観光地の情報</h1>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-spot">投稿者</th>
          <td class="detail-value"><%= link_to @spot.user.nickname, user_path(@spot.user_id) %></td>
        </tr>

        <tr>
          <th class="detail-spot">タイトル</th>
          <td class="detail-value"><%= @spot.title %></td>
        </tr>
        <%# <tr>
          <th class="detail-spot">住所</th>
          <td class="detail-value"><%= @spot.country %></td>
        </tr> %>
      </tbody>
    </table>
    


    <% if user_signed_in? %>
      <% if @spot.user_id == current_user.id %>
        <%= link_to '投稿の編集', edit_spot_path, method: :get, class: "spot-red-btn" %>
        <p class='or-text'>or</p>
        <%= link_to '削除', spot_path, method: :delete, class:'spot-destroy' %>
      <% end %>
    <% end %>

    <%# コメント記入欄 %>
    <div class="container">
      <% if current_user %>
        <%= form_with(model: [@spot, @comment], class:"comment-btn", local: true) do |f| %>
          <%= f.text_area :text, placeholder: "コメントする", class:"comments-text", rows: "2" %>
          <%= f.submit "投稿する", class:"comment-send" %>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
        </strong>
      <% end %>


      <div class="comments">
        <h4 class = "comment-all">＜コメント一覧＞</h4>
        <% if @comments %>
          <% @comments.each do |comment| %>
            <p>
              <strong><%= link_to comment.user.nickname, user_path(comment.user_id) %>：</strong>
              <%= comment.text %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
    <%# コメント記入欄 %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>


<div class="main">
  <p><%= @nickname %>さんの投稿一覧</p>
  <div class="contents">
    <div class="grid">
      <% @spots.each do |spot| %>
        <%= link_to spot_path(spot.id) do %>
          <div class="index-spot">
            <%= image_tag spot.image, class: "spot-img"%>
            <p><%= spot.title %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>